def rcomplement(string):
    bases=list(string)
    bases=bases[::-1]
    bases=['t' if base=='A' else base for base in bases]
    bases=['A' if base=='T' else base for base in bases]
    bases=['c' if base=='G' else base for base in bases]
    bases=['G' if base=='C' else base for base in bases]
    bstring=''.join(bases)
    print(bstring.upper())
rcomplement('AATCGTGATTAACGTATTCGCACCAAACGATACTGTACATAAATCTTTCTCGCCTATAATCAACTTCTGTGGTATATGTTGCAAGGGAATACGCCCGTATTTGTGCGGGGGCGAAACGGAAGTATGGAAACACGTTCGGCCACTGGCTTTCGATGAAGTAATCGATAGGGGTACGAGGCGCGCCCTAGTGCACACGGCCCCTCGTGAGATTGGAAGACCCGTGGGCCGCGTATAATCCTTGTTGCTATCTCTCGCCATCGTAACCGATGAGTCTGTCCGCATCATATGGTTAGATGCAGGGCACTTGTTCATAAGATGGTGGCATTTAGAAAGATTTGATACACCGTATTACCTATACATGTAAGGTCTAGAGCACATACTTACAGATGGTGTAAAATTGGACCCACTCCGACTAGTAATGTTACCACAAAACGTTCTATGCAGGGTAGTGGCATGGTCTGCCGGGTCCGAGCTGCATAGCTATGCAGCTCGGACCCGGCAGACCATTCCCTGCTTCTCTTAATACAGGCAGGTCGTCGGGCGACTCTACGGTAGTCGTGCGTTCATCTCCCTACCAGTAACCCTTGAGAACTCAACAACTATTAGGGTACGACCTCTTACCTCTATTGAATCTGGGCTTATACGAGGCTCCCGCACAATAACGATCAACTACTTAAGTTCTAATCACATGCCGACTCCTTACTAAAGGACCGAAAAAATGGCTAGCTCTATCACAATCGTCGTTGGACATCATTTATCCCATAGATTTTAGTATGACTTTCCAGGCATTTATACAATGTAACTGGGCAATAAATATAAGCTAGACTGGGTGGCGAGGCAAGGCCACCAGAGGCTGTTTAAATATTAAATCAACTCGTAGTGCCCAGCCTTAACACTACTCACTCGCCTATACTTTGGGCTCTAATGATTCTGTTGTTTCATCAATACAGGCGCGATTCC')